site_name: sqlalchemy-csv-writer
site_url: https://raayu83.github.io/sqlalchemy-csv-writer/
repo_url: https://github.com/raayu83/sqlalchemy-csv-writer
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
nav:
  - Introduction: index.md
  - Examples: examples.md
  - API Reference: api.md
markdown_extensions:
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            filters:
            - "!^__del__"
            - "!^__exit__"
extra:
  version:
    provider: mike

