site_name: sqlalchemy-csv-writer
site_url: https://raayu83.github.io/sqlalchemy-csv-writer/
repo_url: https://github.com/raayu83/sqlalchemy-csv-writer
theme:
  name: material
  features:
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
nav:
  - Introduction: index.md
  - Examples:
    - Synchronous: examples/example_sync.md
    - Asynchronous: examples/example_async.md
    - Aynchronous Stream: examples/example_async_stream.md
  - API Reference: api.md
  - Release Notes: changelog.md
  - Coverage report: coverage.md
markdown_extensions:
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - coverage
  - mkdocstrings:
      handlers:
        python:
          options:
            filters:
            - "!^__del__"
            - "!^__exit__"
extra:
  version:
    provider: mike

